
import { test, expect } from '@playwright/test';

const newLab = {
    id: 'e2e-synthetic-lab',
    title: 'E2E Synthetic Test Lab',
    description: 'Automated test entry generated by Playwright.',
    tags: ['Testing', 'Automation'],
    objective: 'Verify CRUD operations.',
    environment: 'Playwright',
    steps: ['Start Test', 'Verify', 'Cleanup'],
    outcome: 'Success',
    createdAt: new Date().toISOString()
};

test.describe('Full App Synthetics', () => {

    test.beforeEach(async ({ page }) => {
        // Seed data before each test
        await page.goto('/');
        await page.evaluate((lab) => {
            const existing = JSON.parse(localStorage.getItem('portfolio_labs') || '[]');
            if (!existing.some(l => l.id === lab.id)) {
                existing.push(lab);
                localStorage.setItem('portfolio_labs', JSON.stringify(existing));
            }
        }, newLab);
        await page.reload();
        await page.waitForLoadState('networkidle');
    });

    test('Public User Journey: View Labs', async ({ page }) => {
        await page.goto('/');
        await expect(page).toHaveTitle(/Portfolio/i);

        // Check Hero (Relaxed check)
        await expect(page.getByText('Cloud & SDDC Infrastructure Engineer')).toBeVisible();

        // Find and Click the Synthetic Lab
        const labCard = page.locator('div', { hasText: 'E2E Synthetic Test Lab' }).first();
        await labCard.scrollIntoViewIfNeeded();
        await expect(labCard).toBeVisible();
        await labCard.click();

        // Check Dialog Content
        await expect(page.getByRole('dialog')).toBeVisible();
        await expect(page.getByText('Verify CRUD operations')).toBeVisible();

        // Close Dialog
        await page.keyboard.press('Escape');
        await expect(page.getByRole('dialog')).not.toBeVisible();
    });

    test('Admin Journey: Verify Content Management', async ({ page }) => {
        await page.goto('/admin');

        // Check Dashboard
        await expect(page.getByRole('tab', { name: 'Profile' })).toBeVisible();

        // Edit Profile (Smoke Test)
        await page.getByLabel('Name').fill('E2E Functioning User');
        await page.reload();
        await page.waitForLoadState('networkidle');
        await expect(page.getByLabel('Name')).toHaveValue('E2E Functioning User');

        // Go to Labs Tab
        await page.getByRole('tab', { name: 'Labs' }).click();
        await expect(page.getByText('E2E Synthetic Test Lab')).toBeVisible();
    });

});
