// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grvwgmgolcbnkeqgtrku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydndnbWdvbGNibmtlcWd0cmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNzIwMDMsImV4cCI6MjA4Njk0ODAwM30.ghC56VJYxabV7nrMePPs89su5DnEeFBGiGPC_o_4Kr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});